### ISSUE TITLE
Need to change abbreviated terms to full words as much as possible

### ISSUE THREAD

**Issue by jforbess** [pvcaptest/pvcaptest#36] opened 2019-09-10 17:53 UTC
The abbreviations in the code base for functions and variables are too difficult to follow and generally unpythonic.

Big picture: don't shorten things by removing vowels, and don't use multiple abbreviations in a single name, especially when they are super overloaded like reg - register, regular, ? ? ? or inv - inverter? no? crazy.

Recommended updates: 

flt = filter
trans = translation or translate, as appropriate
inv = inverted (not sure what this means in terms of translation keys anyway)
cntg_eoy = end_of_year_wrap? could do contiguous_end_of_year, but not sure that's clearer
df_beg = df_start (matches end/df_end then)
ix_ser = ix_series
mnth = month (why take out 1 letter?)
boy = start_of_year (could not parse this without code)
loop_cnt = loop_count
cp_results = captest_results
cprat = captest_ratio
cprat_cpval = ?
reg_fml = regression_fml or regression_formula
reg_trans = regression_variable_translation_table (this is crazy long, but something between  the two, maybe regression_vars_table. Maybe regression_vars_dict, and dict should be used most places trans is used?) 

arguable:
irrRC_balanced = irr_rc_balanced (this is per the PEP8 standard, but I don't feel strongly about it)

**Comment by bt-** [comment] 2019-09-10 18:54
@jforbess Agreed, some of these are not clear at all.  One of the top priorities currently is to increase the test coverage (https://github.com/pvcaptest/pvcaptest/projects/2).  I would like to do that before changing names to help prevent creating issues in the process.

I added a new project for this and linked this issue to it.

**Comment by bt-** [comment] 2020-01-15 14:34
@jforbess, I've been working on making the changes you suggested here this week.  I have changed most of the abbreviations to the names with full words that you suggested.  I came up with different full word names for a few and I have not changed 'inv' or 'trans' yet, see below.

Changed:
- flt - filter; API changes in many places
- cntg_eoy - wrap_year_end; API change
- cp_results - captest_results; API change
- res_summary - captest_results_check_pvalues; API change
- reg_fml - regression_formula; API change
- irrRC_balanced - irr_rc_balanced; API change
- df_beg - df_start
- ix_ser - ix_series
- mnth - month
- months_boy - months_year_start
- months_eoy - months_year_end
- loop_cnt - loop_count
- cprat - cap_ratio
- cprat_cpval - cap_ratio_check_pvalues

**inv**
This is used all over the code as an abbreviation for inverter, which I think seemed acceptable to you?  The one place it was used as an abbreviation for invert was in the function inv_trans_dict, which I have removed since you opened this issue in commit 4df1283d336d2cd7009fc51501e58cfe8795b191.  I removed it because that function was for internal use in the code, but was unused and untested.

**trans**
I borrowed using a dictionary to both group columns and to provide a way to work with shorter column names while retaining the original column name directly from [Pecos](https://pecos.readthedocs.io/en/latest/translation.html).  I think that is where I first picked up the trans abbreviation.  
I agree that the use of 'trans' for 'translation' should be changed, particularly in the API.  But, my preference would be to change this to something more descriptive of the actual function of the translation dictionary within the context of pvcaptest rather than changing to 'translation'.  I am also trying to avoid using python data types in pvcaptest names because of Python's use of duck typing, but I could be convinced that it in this case it makes sense to include 'dict' or 'dictionary' in the name of the attribute that is currently `CapData.trans`.  

The true core function of `CapData.trans` is to hold an assignment of measurement type to each column and group columns, which have the same measurement type.  I would like to change `CapData.trans` to something that reflects this functionality, something like:
- `meas_groups`
- `measurement_groups`, I would prefer something shorter than this
- `column_groups`
- `col_groups`, I don't think 'col' is a great abbreviation

If I try to put myself in the mindset of a new pvcaptest user, I think `column_groups` is the best name.  That seems the most intuitive if I am in the situation of having loaded data and am guessing at attribute names using tab completion.  It is also shorter than 'measurement_groups' and I don't really like the abbreviation of 'meas' for 'measurement.

Pull request #43 is in progress to address this issue.

**Comment by bt-** [comment] 2020-01-22 13:50
I am updating the example capacity test to work with the new names.  While editing the description of what goes on in the background when loading data, I thought of the following options for new names for the `set_translation` method and the `trans` attribute.

`load_data(sets CapData.data, set_translation(sets CapData.trans))` - current names
`load_data(sets CapData.data, infer_measurement_types(sets CapData.measurement_groups))`
`load_data(sets CapData.data, infer_column_types(sets CapData.column_groups))`
`load_data(sets CapData.data, infer_col_types(sets CapData.col_groups))`
`load_data(sets CapData.data, group_cols(sets CapData.col_groups))`
`load_data(sets CapData.data, group_columns(sets CapData.column_groups))` - preferred option

I think the real core functionality here is the grouping of columns.  There are many features of pvcaptest (plotting, aggregation, sensor filtering) that rely on the groups and I've considering adding features upstream or in parallel to the translation grouping to clean up column names (meaning this is feature is really not about linking a short name to the original column name).

I also like how the method names are clearly correlated to the attributes they are setting with the preferred option.

I am going to continue updating this issue with the reasoning behind name changes as I update the example.

**Comment by jforbess** [comment] 2020-01-22 19:28
Oh, I do like the  verb_noun format. I wonder what PEP-8 has to say about
that? It seems inline with the standard.

**Comment by bt-** [comment] 2020-03-07 21:16
Merged #43 to address this issues.  Please see the change log for a list of variable names that were changed.

**Closed by bt-** 2020-03-07 21:16 UTC
Labels: enhancement
