### ISSUE TITLE
Computation of spectral corrections in E2848-13 Appendix A

### ISSUE THREAD

**Issue by markcampanelli** [pvcaptest/pvcaptest#33] opened 2019-08-10 14:44 UTC
I recently started https://github.com/markcampanelli/pvfit-m, an open source Python project to ensure that the computations of spectral mismatch correction factors are valid, consistent, and transparent. I am reaching out to this project regarding the usage of such computations in E2848-13 (esp. Appendix A). I would like to know of any requirements that are currently unmet, and I would be happy to implement functions that would be valuable here. The project is in a very early stage, and I intend to add significant documentation and, once the API is sufficiently stable, publish a v1.0 module on PyPI under the MIT license.

**Comment by bt-** [comment] 2019-08-10 21:33
@markcampanelli thanks for getting in touch.  Currently, there is no functionality in the captest package to calculate spectral mismatch correction factors.  It would be great to be able to import functions from pvfit-m to captest and wrap those into a method or function that makes it easy for a captest end user to apply the spectral corrections when running a capacity test.

I have read through the Appendix A of ASTM E2848-13, but I have not actually applied a correction in practice.  I'm looking at it now trying to understand what the procedure is exactly.  What measured data would go into pvfit-m?  The output would be corrected irradiance measurements of each measured data point?  I'm beginning to think about how the APIs for the two packages would interface.

**Comment by markcampanelli** [comment] 2019-08-12 19:36
@bt- Thanks for your response. My next step I think is to upload some example data to the repo and add documentation in the README.md on how an M computation is done: hopefully an "Up and running in 5 min" tutorial. I will undertake this with the equations in Appendix A of ASTM E2848-13, so as to determine which ones can be solved already and which remain TODO.

**Comment by markcampanelli** [comment] 2019-08-13 19:07
@bt- I have a usage example in [`pvfit-m`'s README](https://github.com/markcampanelli/pvfit-m). I'm not yet efficiently handling the time-series use case, and I still need to make a careful review of E2848 Appendix A to see what other computations might need implementation.

**Comment by jforbess** [comment] 2019-09-10 17:19
@markcampanelli I think your code will do a good job of implementing Appendix A, but the issue is that there is minimal information about the spectral response and spectral components of the irradiance during the ASTM e2848, and that's why it's rarely implemented in actual performance testing (at project substantial completion where I usually see it implemented).

I understand the challenge of using pandas to do the calcs as I saw them in your code, and I think that providing an explicit conversion from pandas to numpy and back as part of the process would be straightforward, and not a reason to avoid doing this. It's the availability of spectral response and spectral irradiance data that rarely exists.

**Comment by markcampanelli** [comment] 2019-09-10 21:52
@jforbess I totally appreciate that the necessary spectral response and irradiance information are not typically available. I have been for a long time now championing an alternative way to measure "effective" irradiance using reference PV devices. If the reference device is sufficiently well matched to the test device, which includes matching the device packaging and operating temperature, then one can avoid the need for spectral response and irradiance information and directly measure the "effective irradiance ratio", denoted F. Furthermore, in my [recent poster](https://pvpmc.sandia.gov/download/7302/), I showed how such a reference device with a calibrated performance model (in terms of F, not G) and an I-V curve tracer (or possibly merely an Isc-Voc measurement) can also estimate the cells' operating temperature T, which should altogether eliminate the need for a MET-station for the capability test (!). Of course, one big hurdle here is getting folks to recast their diode performance models (e.g., PVsyst) in terms of F instead of broadband irradiance G with the attendant (IMHO shaky) corrections relying on angle of incidence, Isc temperature coefficient, spectral mismatch correction factor, and (?) others. I've been looking for partners such as excyte ;) to implement and validate this alternative approach. Any interest in discussing further?

Head's up: I've added such "F-formulated" single-diode modeling to the [pvfit-m repo](https://github.com/markcampanelli/pvfit-m), which now redirects to [https://github.com/markcampanelli/pvfit](https://github.com/markcampanelli/pvfit). Detailed usage examples should be coming soon!

**Comment by bt-** [comment] 2022-08-02 18:29
@markcampanelli, I'm going through the old open issues and working to clean them up. In the last few years of running a lot of capacity tests following ASTM E2848, I haven't seen any parties push for applying the spectral correction in Appendix A, so for now I'm going to close this. I'm happy to re-open and discuss if anyone comes across this use case in practice.

**Closed** 2022-08-02 18:30 UTC
